"use client";

import { useEffect } from "react";
import { useFormState } from "react-dom";
import { useRouter } from "next/navigation";
import { loginAction } from "./login-actions";

const initialState = { success: false, error: "" };

export function LoginForm() {
  const router = useRouter();
  const [state, formAction] = useFormState(loginAction, initialState);

  useEffect(() => {
    if (state?.success) router.push("/");
  }, [state?.success, router]);

  return (
    <form action={formAction} style={{ display: "grid", gap: "12px", maxWidth: 320 }}>
      <label style={{ display: "grid", gap: 6 }}>
        <span>Admin password</span>
        <input name="password" type="password" required placeholder="Generated by installer" />
      </label>
      {state?.error ? <div style={{ color: "crimson" }}>{state.error}</div> : null}
      <button type="submit" style={{ padding: "10px 16px" }}>Login</button>
    </form>
  );
}
