import { redirect } from "next/navigation";
import { hasSession } from "../lib/session.js";
import { LoginForm } from "./login-form";

export default function LoginPage() {
  if (hasSession()) redirect("/");

  return (
    <main>
      <h1>Voxeil Panel</h1>
      <p>Enter the admin password generated by the installer.</p>
      <LoginForm />
    </main>
  );
}
