export const SITE_ANNOTATIONS = {
  domain: "voxeil.com/domain",
  tlsEnabled: "voxeil.com/tls-enabled",
  tlsIssuer: "voxeil.com/tls-issuer",
  image: "voxeil.com/image",
  containerPort: "voxeil.com/container-port",
  cpu: "voxeil.com/cpu",
  ramGi: "voxeil.com/ramGi",
  diskGi: "voxeil.com/diskGi",
  backupEnabled: "voxeil.com/backup-enabled",
  mailEnabled: "voxeil.com/mail-enabled",
  mailProvider: "voxeil.com/mail-provider",
  mailDomain: "voxeil.com/mail-domain",
  mailStatus: "voxeil.com/mail-status",
  mailLastError: "voxeil.com/mail-last-error",
  dbEnabled: "voxeil.com/db-enabled",
  dbName: "voxeil.com/db-name",
  dbUser: "voxeil.com/db-user",
  dbSecret: "voxeil.com/db-secret"
} as const;
