apiVersion: v1
kind: LimitRange
metadata:
  name: site-limits
  # namespace is set by the controller per tenant
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 1000m
        memory: 1Gi
      min:
        cpu: 50m
        memory: 64Mi
